In [ ]:
import numpy as np

# Create a clear 3×5 test array
arr = np.array([
    [ 1,  2,  3,  4,  5],
    [10, 20, 30, 40, 50],
    [100,200,300,400,500]
])

print("FULL ARRAY:")
print(arr)

print("\n1) arr[:, 2]  → every row, column 2")
print(arr[:, 2])   # axis=1 operation (column slice)

print("\n2) arr[1, :]  → row 1, every column")
print(arr[1, :])   # axis=0 operation (row slice)

print("\n3) arr[:, :]  → whole array")
print(arr[:, :])   # entire array (no slicing)

print("\n4) arr[0:2, :]  → rows 0 and 1, all columns")
print(arr[0:2, :])

print("\n5) arr[:, 1:4]  → all rows, columns 1 to 3")
print(arr[:, 1:4])

print("\n6) arr[1:3, 2:5]  → rows 1-2, columns 2-4")
print(arr[1:3, 2:5])


FULL ARRAY:
[[  1   2   3   4   5]
 [ 10  20  30  40  50]
 [100 200 300 400 500]]

6) arr[1:3, 2:5]  → rows 1-2, columns 2-4
[[ 30  40  50]
 [300 400 500]]
